---
- name: cloud-init setup
  hosts: coreos
  become: yes
  tasks:
    - name: set hostname
      command: hostnamectl set-hostname {{ inventory_hostname }}
      notify:
        - restart server
        - wait for server to restart
  handlers:
    - name: restart server
      command: shutdown -r now "Reboot triggered by Ansible"
      async: 0
      poll: 0
      ignore_errors: true
    - name: wait for server to restart
      local_action:
        module: wait_for 
        host: "{{ ansible_host | default(inventory_hostname) }}" 
        port: "{{ ansible_port }}"
        delay: 5
        timeout: 30 
      become: no
          
# vim:ft=ansible:
